server_name: example.com

# Set the username to use to authenticate with the MQTT broker. Default is "key".
#mqtt_username: username

# Set the password to use to authenticate with the MQTT broker. Default is the value of the
# "secret_key" config option.
#mqtt_password: password
